OPENAI_API_KEY = "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"

[connections.snowpark]
user = "EULERIANKNIGHT"
password = "Rashimanshu@1707"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "ZNBAHXU-KEB62628"